# Generated by Django 5.1.2 on 2024-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet_name', models.CharField(max_length=50, verbose_name='作者名')),
                ('poetry_name', models.CharField(max_length=20, verbose_name='古诗名')),
                ('poetry_content', models.TextField(verbose_name='古诗内容')),
            ],
        ),
    ]
