# Generated by Django 5.1.2 on 2024-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet_name', models.CharField(max_length=100, verbose_name='诗人名')),
                ('poet_info', models.TextField(verbose_name='诗人生平')),
                ('poet_works', models.JSONField()),
            ],
            options={
                'verbose_name': '诗人',
                'db_table': 'poet_info',
            },
        ),
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet_name', models.CharField(max_length=10, verbose_name='诗人名')),
                ('poet_dynasty', models.CharField(max_length=5, verbose_name='朝代')),
                ('poetry_name', models.CharField(max_length=50, verbose_name='古诗名')),
                ('poetry_info', models.TextField(verbose_name='古诗内容')),
            ],
            options={
                'verbose_name': '古诗',
                'db_table': 'poetry_info',
            },
        ),
    ]
