# Generated by Django 5.1.2 on 2024-10-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(max_length=4096, verbose_name='内容')),
                ('reply_create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=32, verbose_name='标题')),
                ('topic_content', models.TextField(max_length=4096, verbose_name='内容')),
                ('topic_create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('topic_topped', models.BooleanField(default=False, verbose_name='置顶帖子')),
            ],
        ),
    ]
